### ISSUE TITLE
Style doesn't update if the entity changes

### ISSUE THREAD

**Issue by afonsolage** [afonsolage/bevy_ecss#39]
If the entity changes, the new matching style doesn't update.

Given the following CSS:
```css
#red-bg {
    background-color: red;
}

#blue-bg {
    background-color: blue;
}
```

If I change some entity during the runtime from `Name("red-bg")` to `Name("blue-bg")` the style doesn't update. I have to manually update the `StyleSheet` in order to do so.
