### ISSUE TITLE
My StyleSheets aren't cascading to new children

### ISSUE THREAD

**Issue by Zeenobit** [afonsolage/bevy_ecss#61]
I'm trying to use `bevy_ecss` in my project, but for some reason my stylesheets aren't cascading to child nodes that are added after the initial UI setup.

I have some entities that spawn in the world, and each entities is associated with a named button. All buttons have the exact same name: `ControlButton` and are added to a parent node named `ControlButtonContainer`.

The system which adds the buttons on entity spawn runs in `Update` schedule.
The systems which spawns the button container (for which the cascading does seem to work) run in `Startup` schedule.

In my CSS, I have:
```css
#ControlButtonContainer {
    flex-direction: row;
    align-self: flex-start;
    width: 100%;
    padding: 0 8px 0px 8px; /* Left Top Right Bottom */
    background-color: yellow;
}

#ControlButton {
    width: 64px;
    height: 64px;
    margin: 0px 0px 0px 8px; /* Top Right Bottom Left */
    background-color: purple;
}
```

For some reason the `ControlButtonContainer` gets the correct style. But `ControlButton` never gets the correct style.

I can work around the issue by just adding the style sheet to every `ControlButton`. This is what makes me think the issue is from the library and not my code.

Is there something I'm missing?

I also can't seem to get hot reload to work either (changing the CSS file and saving doesn't do anything). I'm also not sure why I'm getting inconsistent ordering between `padding` and `margin` in my CSS file (which I figured through pure trial and error). I'm not sure if these issues are related!

This is how I'm initializing the plugin:
```rust
app.add_plugins(EcssPlugin::with_hot_reload());
```

Any help would be appreciated!
